#!/usr/bin/env python3
"""
Exact coefficient-covariance propagation without enumerating C columns.

This script computes the parameter-averaged Fourier-coefficient covariance

    Cov[a_omega, a_omega']

for PQCs with commuting Pauli encoders and Pauli/controlled-rotation trainer
blocks.  It does *not* build the full circuit harmonic matrix C.  Instead it
uses the identity

    Cov[a] = C P C^dagger

and evaluates the quadratic form directly by a two-copy, parameter-twirled
Heisenberg propagation.  This avoids storing the exponentially large k-support.

The method is exact for Pauli rotations under uniform parameter averaging.  For
controlled RX/RZ gates it uses deterministic Fourier quadrature of the local
2-qubit twirl map; with a sufficient number of quadrature points this is exact
up to floating point error for the trigonometric polynomial generated by the
controlled rotation.

Typical use:

    python exact_covariance_twirled.py \
        --out_dir exact_cov/CIRCUIT_18_n6d4 \
        --ansatz CIRCUIT_18 --n_qubits 6 --train_depth 4 \
        --encoder_axis RX --obs_kind OZ \
        --combine_tol 1e-14 --progress

Optional Monte Carlo validation against ansatze.py/PennyLane:

    python exact_covariance_twirled.py ... \
        --ansatze_path /path/to/repo_or_module_dir \
        --validate_mc_samples 4096 --n_x_mc 128

Important convention:
    The standard Pauli rotations are 2*pi-periodic at the expectation-value
    level.  PennyLane CRX/CRZ gates can generate half-angle terms; if you want
    their full parameter-torus periodicity, use --theta_period 4pi.  If your MC
    code samples theta in [0,2*pi), leave the default --theta_period 2pi so the
    exact average matches that ensemble.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np


def _fmt_seconds(seconds: float) -> str:
    """Human-readable duration for progress/ETA messages."""
    if not np.isfinite(seconds) or seconds < 0:
        return "?"
    seconds = int(round(float(seconds)))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h:d}h{m:02d}m{s:02d}s"
    if m:
        return f"{m:d}m{s:02d}s"
    return f"{s:d}s"


def _print_step_progress(
    label: str,
    step: int,
    total: int,
    states: int,
    t0: float,
    last_report_t: float,
    last_report_step: int,
    last_report_states: int,
) -> Tuple[float, int, int]:
    """Print elapsed time, a linear ETA, a recent-window ETA, and state growth.

    The recent-window ETA is deliberately labelled as an estimate only: for the
    two-copy propagation, future cost can change abruptly when the state
    dictionary starts growing or collapsing.
    """
    now = time.time()
    elapsed = now - t0
    remaining = max(0, int(total) - int(step))
    avg_eta = (elapsed / max(1, int(step))) * remaining
    recent_steps = max(1, int(step) - int(last_report_step))
    recent_eta = ((now - last_report_t) / recent_steps) * remaining
    growth = (float(states) / float(last_report_states)) if last_report_states > 0 else float("inf")
    growth_txt = "inf" if not np.isfinite(growth) else f"{growth:.2f}x"
    print(
        f"{label} step {step:4d}/{total} "
        f"states={states} growth={growth_txt} "
        f"elapsed={_fmt_seconds(elapsed)} "
        f"eta(avg)={_fmt_seconds(avg_eta)} eta(recent)={_fmt_seconds(recent_eta)}",
        flush=True,
    )
    return now, int(step), int(states)

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception:  # pragma: no cover
    plt = None

# ---------------------------------------------------------------------------
# Packed Pauli algebra
# ---------------------------------------------------------------------------

# I=0, X=1, Y=2, Z=3, encoded in two bits per qubit.
I, X, Y, Z = 0, 1, 2, 3
CHAR_TO_CODE = {"I": I, "X": X, "Y": Y, "Z": Z}
CODE_TO_CHAR = {v: k for k, v in CHAR_TO_CODE.items()}

# (phase, product)
_MUL = {
    (I, I): (1+0j, I), (I, X): (1+0j, X), (I, Y): (1+0j, Y), (I, Z): (1+0j, Z),
    (X, I): (1+0j, X), (Y, I): (1+0j, Y), (Z, I): (1+0j, Z),
    (X, X): (1+0j, I), (Y, Y): (1+0j, I), (Z, Z): (1+0j, I),
    (X, Y): (1j, Z),  (Y, Z): (1j, X),  (Z, X): (1j, Y),
    (Y, X): (-1j, Z), (Z, Y): (-1j, X), (X, Z): (-1j, Y),
}


def get_code(p: int, q: int) -> int:
    return (int(p) >> (2 * int(q))) & 0b11


def set_code(p: int, q: int, code: int) -> int:
    q = int(q)
    mask = 0b11 << (2 * q)
    return (int(p) & ~mask) | ((int(code) & 0b11) << (2 * q))


def pauli_on(n: int, axis: str, wire: int) -> int:
    code = CHAR_TO_CODE[axis[-1] if axis.startswith("R") else axis]
    return set_code(0, wire, code)


def pauli_zz(n: int, a: int, b: int) -> int:
    return set_code(set_code(0, a, Z), b, Z)


def pauli_to_str(p: int, n: int) -> str:
    return "".join(CODE_TO_CHAR[get_code(p, q)] for q in range(n))


def local_index_2q(p: int, a: int, b: int) -> int:
    return get_code(p, a) + 4 * get_code(p, b)


def set_local_2q(p: int, a: int, b: int, local_idx: int) -> int:
    c0 = int(local_idx) % 4
    c1 = int(local_idx) // 4
    return set_code(set_code(p, a, c0), b, c1)


def commute(p: int, q: int, n: int) -> bool:
    anti = 0
    for w in range(n):
        a = get_code(p, w)
        b = get_code(q, w)
        if a != I and b != I and a != b:
            anti += 1
    return (anti % 2) == 0


def pauli_mul(p: int, q: int, n: int) -> Tuple[complex, int]:
    phase = 1 + 0j
    out = 0
    for w in range(n):
        ph, c = _MUL[(get_code(p, w), get_code(q, w))]
        phase *= ph
        out = set_code(out, w, c)
    return phase, out


def input_expectation_zero(p: int, n: int) -> complex:
    for w in range(n):
        c = get_code(p, w)
        if c not in (I, Z):
            return 0 + 0j
    return 1 + 0j


# ---------------------------------------------------------------------------
# Clifford conjugation in packed representation
# ---------------------------------------------------------------------------


def conjugate_by_cnot(q: int, n: int, control: int, target: int) -> Tuple[complex, int]:
    acc = 0
    coeff = 1 + 0j
    for w in range(n):
        ch = get_code(q, w)
        if ch == I:
            continue
        img = 0
        if w == control:
            if ch == X:
                img = set_code(set_code(0, control, X), target, X)
            elif ch == Y:
                img = set_code(set_code(0, control, Y), target, X)
            elif ch == Z:
                img = set_code(0, control, Z)
        elif w == target:
            if ch == X:
                img = set_code(0, target, X)
            elif ch == Y:
                img = set_code(set_code(0, control, Z), target, Y)
            elif ch == Z:
                img = set_code(set_code(0, control, Z), target, Z)
        else:
            img = set_code(0, w, ch)
        ph, acc = pauli_mul(acc, img, n)
        coeff *= ph
    return coeff, acc


def conjugate_by_cz(q: int, n: int, a: int, b: int) -> Tuple[complex, int]:
    acc = 0
    coeff = 1 + 0j
    for w in range(n):
        ch = get_code(q, w)
        if ch == I:
            continue
        img = 0
        if w == a:
            if ch == X:
                img = set_code(set_code(0, a, X), b, Z)
            elif ch == Y:
                img = set_code(set_code(0, a, Y), b, Z)
            elif ch == Z:
                img = set_code(0, a, Z)
        elif w == b:
            if ch == X:
                img = set_code(set_code(0, a, Z), b, X)
            elif ch == Y:
                img = set_code(set_code(0, a, Z), b, Y)
            elif ch == Z:
                img = set_code(0, b, Z)
        else:
            img = set_code(0, w, ch)
        ph, acc = pauli_mul(acc, img, n)
        coeff *= ph
    return coeff, acc


# ---------------------------------------------------------------------------
# Operations and circuit construction
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Operation:
    kind: str                         # rot, cnot, cz, cr
    pauli: Optional[int] = None        # for Pauli rotations
    var_kind: Optional[str] = None     # x or theta for rot; theta for cr
    var_index: Optional[int] = None
    omega_scale: int = 1
    wires: Tuple[int, ...] = ()        # cnot/cz: (a,b), cr: (control,target)
    axis: Optional[str] = None         # cr axis: RX or RZ


def params_per_train_block(ansatz: str, n: int) -> int:
    if ansatz in ("YZY", "YZY_ENTANGLING", "HEA", "CIRCUIT_MULTIOBS", "CIRCUIT_ENTFIRST"):
        return 3 * n
    if ansatz == "CIRCUIT_15":
        return 2 * n
    if ansatz in ("CIRCUIT_16", "CIRCUIT_17"):
        return 2 * n + (n - 1)
    if ansatz in ("CIRCUIT_18", "CIRCUIT_19"):
        return 3 * n
    if ansatz == "CIRCUIT_ZZ":
        return 2 * n + n // 2
    raise ValueError(f"Unsupported ansatz for exact covariance: {ansatz}")


def add_rot(ops: List[Operation], n: int, axis: str, wire: int, var_kind: str, var_index: Optional[int] = None, omega_scale: int = 1) -> None:
    ops.append(Operation("rot", pauli=pauli_on(n, axis, wire), var_kind=var_kind, var_index=var_index, omega_scale=int(omega_scale)))


def add_cnot_ring(ops: List[Operation], n: int) -> None:
    for i in range(0, n - 1, 2):
        ops.append(Operation("cnot", wires=(i, i + 1)))
    for i in range(1, n - 1, 2):
        ops.append(Operation("cnot", wires=(i, i + 1)))
    if n > 2:
        ops.append(Operation("cnot", wires=(n - 1, 0)))


def add_cnot_all_to_all(ops: List[Operation], n: int) -> None:
    for i in range(n - 1):
        for j in range(i + 1, n):
            ops.append(Operation("cnot", wires=(i, j)))


def strobl_controlled_pairs(ansatz: str, n: int) -> List[Tuple[int, int]]:
    """Return (control, target) pairs for the corrected circuit 16--19 convention.

    For n=4:
      C16/17: (1->0), (3->2), (2->1)      open neighbouring pattern
      C18/19: (3->0), (2->3), (1->2), (0->1) full ring
    """
    if n < 2:
        raise ValueError("Controlled Strobl circuits require n>=2")
    if ansatz in ("CIRCUIT_16", "CIRCUIT_17"):
        targets = [0] + list(range(n - 2, 0, -1))
        return [(t + 1, t) for t in targets]
    if ansatz in ("CIRCUIT_18", "CIRCUIT_19"):
        targets = [0] + list(range(n - 1, 0, -1))
        return [((t - 1) % n, t) for t in targets]
    raise ValueError(ansatz)


def build_forward_ops(ansatz: str, n: int, L: int, d: int, encoder_axis: str, encoder_scale: int) -> Tuple[List[Operation], int]:
    p_block = params_per_train_block(ansatz, n)
    m = L * d * p_block
    ops: List[Operation] = []
    theta_base = 0
    for _layer in range(L):
        for w in range(n):
            add_rot(ops, n, encoder_axis, w, "x", None, encoder_scale)
        for _block in range(d):
            t0 = theta_base
            if ansatz == "YZY":
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + 0)
                    add_rot(ops, n, "RZ", w, "theta", idx + 1)
                    add_rot(ops, n, "RY", w, "theta", idx + 2)
                    idx += 3
            elif ansatz == "YZY_ENTANGLING":
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + 0)
                    add_rot(ops, n, "RZ", w, "theta", idx + 1)
                    add_rot(ops, n, "RY", w, "theta", idx + 2)
                    idx += 3
                add_cnot_all_to_all(ops, n)
            elif ansatz == "HEA":
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + 0)
                    add_rot(ops, n, "RZ", w, "theta", idx + 1)
                    add_rot(ops, n, "RY", w, "theta", idx + 2)
                    idx += 3
                add_cnot_ring(ops, n)
            elif ansatz == "CIRCUIT_15":
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx); idx += 1
                add_cnot_ring(ops, n)
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx); idx += 1
                add_cnot_ring(ops, n)
            elif ansatz in ("CIRCUIT_16", "CIRCUIT_17", "CIRCUIT_18", "CIRCUIT_19"):
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RX", w, "theta", idx + 0)
                    add_rot(ops, n, "RZ", w, "theta", idx + 1)
                    idx += 2
                cr_axis = "RZ" if ansatz in ("CIRCUIT_16", "CIRCUIT_18") else "RX"
                for control, target in strobl_controlled_pairs(ansatz, n):
                    ops.append(Operation("cr", var_kind="theta", var_index=idx, wires=(control, target), axis=cr_axis))
                    idx += 1
                if idx != t0 + p_block:
                    raise RuntimeError(f"Internal parameter count mismatch for {ansatz}: consumed {idx-t0}, expected {p_block}")
            elif ansatz == "CIRCUIT_ZZ":
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + w)
                idx += n
                for pair in range(n // 2):
                    ops.append(Operation("rot", pauli=pauli_zz(n, 2 * pair, 2 * pair + 1), var_kind="theta", var_index=idx + pair))
                idx += n // 2
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + w)
            elif ansatz == "CIRCUIT_MULTIOBS":
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + 0)
                    add_rot(ops, n, "RZ", w, "theta", idx + 1)
                    add_rot(ops, n, "RY", w, "theta", idx + 2)
                    idx += 3
            elif ansatz == "CIRCUIT_ENTFIRST":
                add_cnot_ring(ops, n)
                idx = t0
                for w in range(n):
                    add_rot(ops, n, "RY", w, "theta", idx + 0)
                    add_rot(ops, n, "RZ", w, "theta", idx + 1)
                    add_rot(ops, n, "RY", w, "theta", idx + 2)
                    idx += 3
            else:
                raise ValueError(ansatz)
            theta_base += p_block
    return ops, m


# ---------------------------------------------------------------------------
# Observables
# ---------------------------------------------------------------------------


def observable_terms(n: int, obs_kind: str, ansatz: str) -> List[Tuple[complex, int]]:
    kind = "OZZ" if ansatz == "CIRCUIT_MULTIOBS" else obs_kind
    out: List[Tuple[complex, int]] = []
    if kind == "OX":
        for w in range(n):
            out.append((1.0 / n, pauli_on(n, "X", w)))
    elif kind == "OY":
        for w in range(n):
            out.append((1.0 / n, pauli_on(n, "Y", w)))
    elif kind == "OZ":
        for w in range(n):
            out.append((1.0 / n, pauli_on(n, "Z", w)))
    elif kind == "OZZ":
        pairs = [(i, j) for i in range(n) for j in range(i + 1, n)]
        if not pairs:
            out.append((1.0, pauli_on(n, "Z", 0)))
        else:
            scale = 2.0 / (n * (n - 1))
            for i, j in pairs:
                out.append((scale, pauli_zz(n, i, j)))
    else:
        raise ValueError(obs_kind)
    return out


# ---------------------------------------------------------------------------
# Controlled-rotation local maps by deterministic quadrature
# ---------------------------------------------------------------------------

_PAULI_1Q = [
    np.array([[1, 0], [0, 1]], dtype=np.complex128),
    np.array([[0, 1], [1, 0]], dtype=np.complex128),
    np.array([[0, -1j], [1j, 0]], dtype=np.complex128),
    np.array([[1, 0], [0, -1]], dtype=np.complex128),
]
_PAULI_2Q = [np.kron(_PAULI_1Q[i], _PAULI_1Q[j]) for j in range(4) for i in range(4)]
# local index = code_control + 4*code_target, matching kron(control, target)


def cr_unitary(axis: str, theta: float) -> np.ndarray:
    axis = str(axis).upper()
    if axis == "RZ":
        rz = np.array([[np.exp(-0.5j * theta), 0], [0, np.exp(0.5j * theta)]], dtype=np.complex128)
        U = np.eye(4, dtype=np.complex128)
        U[2:4, 2:4] = rz
        return U
    if axis == "RX":
        c = math.cos(theta / 2.0)
        s = math.sin(theta / 2.0)
        rx = np.array([[c, -1j * s], [-1j * s, c]], dtype=np.complex128)
        U = np.eye(4, dtype=np.complex128)
        U[2:4, 2:4] = rx
        return U
    raise ValueError(f"Unsupported controlled rotation axis: {axis}")


def single_cr_conj_coeffs(axis: str, theta: float) -> np.ndarray:
    """Return coeffs[in_local, out_local] for U^dag P_in U."""
    U = cr_unitary(axis, theta)
    Ud = U.conj().T
    coeffs = np.zeros((16, 16), dtype=np.complex128)
    for a, P in enumerate(_PAULI_2Q):
        M = Ud @ P @ U
        # Pauli basis is orthogonal: coeff = Tr(P_b M)/4.
        for b, B in enumerate(_PAULI_2Q):
            coeffs[a, b] = np.trace(B @ M) / 4.0
    return coeffs


def build_cr_maps(axis: str, n_quad: int, theta_period: float, tol: float) -> Tuple[List[List[Tuple[int, complex]]], List[List[Tuple[int, int, complex]]]]:
    """Build single-copy and two-copy averaged local maps for CR axis.

    single_map[a] = [(b, coeff_avg)] for E_theta[U^dag P_a U]
    pair_map[a*16+b] = [(a_out,b_out, coeff_avg)] for
        E_theta[(U^dag P_a U) tensor (U^dag P_b U)].
    """
    single_acc = np.zeros((16, 16), dtype=np.complex128)
    pair_acc = np.zeros((16, 16, 16, 16), dtype=np.complex128)
    for j in range(int(n_quad)):
        theta = theta_period * (j + 0.5) / float(n_quad)
        A = single_cr_conj_coeffs(axis, theta)
        single_acc += A
        # pair_acc[a,b,c,d] += A[a,c] * A[b,d]
        pair_acc += A[:, None, :, None] * A[None, :, None, :]
    single_acc /= float(n_quad)
    pair_acc /= float(n_quad)

    single_map: List[List[Tuple[int, complex]]] = []
    for a in range(16):
        entries = [(b, single_acc[a, b]) for b in range(16) if abs(single_acc[a, b]) > tol]
        single_map.append(entries)

    pair_map: List[List[Tuple[int, int, complex]]] = []
    for a in range(16):
        for b in range(16):
            entries = []
            for c in range(16):
                for d in range(16):
                    val = pair_acc[a, b, c, d]
                    if abs(val) > tol:
                        entries.append((c, d, val))
            pair_map.append(entries)
    return single_map, pair_map


# ---------------------------------------------------------------------------
# Single-copy mean propagation
# ---------------------------------------------------------------------------

SingleState = Dict[Tuple[int, int], complex]          # (pauli, omega) -> coeff
PairState = Dict[Tuple[int, int, int, int], complex]  # (pauli1, pauli2, om1, om2) -> coeff


def add_acc(acc: Dict[tuple, complex], key: tuple, val: complex, tol: float) -> None:
    if abs(val) <= tol:
        return
    new = acc.get(key, 0 + 0j) + val
    if abs(new) <= tol:
        acc.pop(key, None)
    else:
        acc[key] = new


def branch_x_single(p: int, coeff: complex, omega: int, op: Operation, n: int) -> List[Tuple[int, complex, int]]:
    assert op.pauli is not None
    P = op.pauli
    if commute(P, p, n):
        return [(p, coeff, omega)]
    out: List[Tuple[int, complex, int]] = []
    # cos branch
    for sgn, fac in ((+1, 0.5+0j), (-1, 0.5+0j)):
        out.append((p, coeff * fac, omega + sgn * int(op.omega_scale)))
    # sin branch: i P Q sin(x)
    ph, R = pauli_mul(P, p, n)
    base = coeff * 1j * ph
    for sgn, fac in ((+1, 1/(2j)), (-1, -1/(2j))):
        out.append((R, base * fac, omega + sgn * int(op.omega_scale)))
    return out


def theta_average_single_pauli(p: int, coeff: complex, omega: int, op: Operation, n: int) -> List[Tuple[int, complex, int]]:
    assert op.pauli is not None
    if commute(op.pauli, p, n):
        return [(p, coeff, omega)]
    # E[cos theta] = E[sin theta] = 0.
    return []


def apply_single_clifford(p: int, coeff: complex, omega: int, op: Operation, n: int) -> Tuple[int, complex, int]:
    if op.kind == "cnot":
        ph, q = conjugate_by_cnot(p, n, op.wires[0], op.wires[1])
    elif op.kind == "cz":
        ph, q = conjugate_by_cz(p, n, op.wires[0], op.wires[1])
    else:
        raise ValueError(op.kind)
    return q, coeff * ph, omega


def exact_mean(ops: Sequence[Operation], obs: Sequence[Tuple[complex, int]], n: int, cr_single_maps: Dict[str, List[List[Tuple[int, complex]]]], tol: float, max_states: int, progress: bool) -> Tuple[np.ndarray, np.ndarray, SingleState]:
    state: SingleState = {(p, 0): complex(c) for c, p in obs}
    t0 = time.time()
    last_report_t = t0
    last_report_step = 0
    last_report_states = max(1, len(state))
    for step, op in enumerate(reversed(ops), start=1):
        new: SingleState = {}
        for (p, om), c in state.items():
            if op.kind == "rot" and op.var_kind == "x":
                for p2, c2, om2 in branch_x_single(p, c, om, op, n):
                    add_acc(new, (p2, om2), c2, tol)
            elif op.kind == "rot" and op.var_kind == "theta":
                for p2, c2, om2 in theta_average_single_pauli(p, c, om, op, n):
                    add_acc(new, (p2, om2), c2, tol)
            elif op.kind in ("cnot", "cz"):
                p2, c2, om2 = apply_single_clifford(p, c, om, op, n)
                add_acc(new, (p2, om2), c2, tol)
            elif op.kind == "cr":
                axis = str(op.axis)
                control, target = op.wires
                lin = local_index_2q(p, control, target)
                for lout, fac in cr_single_maps[axis][lin]:
                    p2 = set_local_2q(p, control, target, lout)
                    add_acc(new, (p2, om), c * fac, tol)
            else:
                raise ValueError(op)
        state = new
        if len(state) > max_states:
            raise RuntimeError(f"Mean propagation exceeded --max_states={max_states} at step {step}; current states={len(state)}")
        if progress and (step == 1 or step == len(ops) or step % 5 == 0):
            last_report_t, last_report_step, last_report_states = _print_step_progress(
                "mean", step, len(ops), len(state), t0,
                last_report_t, last_report_step, last_report_states,
            )
    mean_dict: Dict[int, complex] = defaultdict(complex)
    terminal = {}
    for (p, om), c in state.items():
        e = input_expectation_zero(p, n)
        if abs(e) > 0:
            val = c * e
            mean_dict[int(om)] += val
            terminal[(p, om)] = val
    omegas = np.asarray(sorted(mean_dict), dtype=int)
    mean = np.asarray([mean_dict[int(o)] for o in omegas], dtype=np.complex128)
    return omegas, mean, terminal


# ---------------------------------------------------------------------------
# Two-copy second-moment propagation
# ---------------------------------------------------------------------------


def theta_average_pair_pauli(p1: int, p2: int, coeff: complex, om1: int, om2: int, op: Operation, n: int) -> List[Tuple[int, int, complex, int, int]]:
    assert op.pauli is not None
    P = op.pauli
    a1 = not commute(P, p1, n)
    a2 = not commute(P, p2, n)
    if not a1 and not a2:
        return [(p1, p2, coeff, om1, om2)]
    if a1 != a2:
        # One side has cos/sin and the other is constant; the parameter average is zero.
        return []
    # both anticommute: average cos^2 and sin^2 survive.
    ph1, r1 = pauli_mul(P, p1, n)
    ph2, r2 = pauli_mul(P, p2, n)
    coscos = coeff * 0.5
    sinsin = coeff * (1j * ph1) * (1j * ph2) * 0.5
    return [(p1, p2, coscos, om1, om2), (r1, r2, sinsin, om1, om2)]


def branch_x_pair_one_copy(p1: int, p2: int, coeff: complex, om1: int, om2: int, op: Operation, n: int, copy: int) -> List[Tuple[int, int, complex, int, int]]:
    if copy == 1:
        branches = branch_x_single(p1, coeff, om1, op, n)
        return [(q1, p2, c, qom, om2) for q1, c, qom in branches]
    branches = branch_x_single(p2, coeff, om2, op, n)
    return [(p1, q2, c, om1, qom) for q2, c, qom in branches]


def apply_pair_clifford(p1: int, p2: int, coeff: complex, om1: int, om2: int, op: Operation, n: int) -> Tuple[int, int, complex, int, int]:
    if op.kind == "cnot":
        ph1, q1 = conjugate_by_cnot(p1, n, op.wires[0], op.wires[1])
        ph2, q2 = conjugate_by_cnot(p2, n, op.wires[0], op.wires[1])
    elif op.kind == "cz":
        ph1, q1 = conjugate_by_cz(p1, n, op.wires[0], op.wires[1])
        ph2, q2 = conjugate_by_cz(p2, n, op.wires[0], op.wires[1])
    else:
        raise ValueError(op.kind)
    return q1, q2, coeff * ph1 * ph2, om1, om2


def exact_second_moment(ops: Sequence[Operation], obs: Sequence[Tuple[complex, int]], n: int, cr_pair_maps: Dict[str, List[List[Tuple[int, int, complex]]]], tol: float, max_states: int, progress: bool) -> Tuple[Dict[Tuple[int, int], complex], PairState]:
    state: PairState = {}
    for c1, p1 in obs:
        for c2, p2 in obs:
            add_acc(state, (p1, p2, 0, 0), complex(c1) * complex(c2), tol)
    t0 = time.time()
    last_report_t = t0
    last_report_step = 0
    last_report_states = max(1, len(state))
    for step, op in enumerate(reversed(ops), start=1):
        new: PairState = {}
        for (p1, p2, om1, om2), c in state.items():
            if op.kind == "rot" and op.var_kind == "x":
                # U(x) on copy 1 and U(y) on copy 2, with independent Fourier variables.
                tmp = branch_x_pair_one_copy(p1, p2, c, om1, om2, op, n, copy=1)
                for q1, q2, ctmp, qom1, qom2 in tmp:
                    for r1, r2, c2, rom1, rom2 in branch_x_pair_one_copy(q1, q2, ctmp, qom1, qom2, op, n, copy=2):
                        add_acc(new, (r1, r2, rom1, rom2), c2, tol)
            elif op.kind == "rot" and op.var_kind == "theta":
                for q1, q2, c2, qom1, qom2 in theta_average_pair_pauli(p1, p2, c, om1, om2, op, n):
                    add_acc(new, (q1, q2, qom1, qom2), c2, tol)
            elif op.kind in ("cnot", "cz"):
                q1, q2, c2, qom1, qom2 = apply_pair_clifford(p1, p2, c, om1, om2, op, n)
                add_acc(new, (q1, q2, qom1, qom2), c2, tol)
            elif op.kind == "cr":
                axis = str(op.axis)
                control, target = op.wires
                lin1 = local_index_2q(p1, control, target)
                lin2 = local_index_2q(p2, control, target)
                for lout1, lout2, fac in cr_pair_maps[axis][lin1 * 16 + lin2]:
                    q1 = set_local_2q(p1, control, target, lout1)
                    q2 = set_local_2q(p2, control, target, lout2)
                    add_acc(new, (q1, q2, om1, om2), c * fac, tol)
            else:
                raise ValueError(op)
        state = new
        if len(state) > max_states:
            raise RuntimeError(f"Second-moment propagation exceeded --max_states={max_states} at step {step}; current states={len(state)}")
        if progress and (step == 1 or step == len(ops) or step % 5 == 0):
            last_report_t, last_report_step, last_report_states = _print_step_progress(
                "pair", step, len(ops), len(state), t0,
                last_report_t, last_report_step, last_report_states,
            )
    moment: Dict[Tuple[int, int], complex] = defaultdict(complex)
    terminal: PairState = {}
    for (p1, p2, om1, om2), c in state.items():
        e1 = input_expectation_zero(p1, n)
        e2 = input_expectation_zero(p2, n)
        if abs(e1) > 0 and abs(e2) > 0:
            val = c * e1 * e2
            moment[(int(om1), int(om2))] += val
            terminal[(p1, p2, om1, om2)] = val
    return dict(moment), terminal


# ---------------------------------------------------------------------------
# Assembly, plotting, validation
# ---------------------------------------------------------------------------


def assemble_matrices(mean_dict: Dict[int, complex], moment: Dict[Tuple[int, int], complex]) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    omega_set = set(mean_dict.keys())
    for om1, om2 in moment:
        omega_set.add(int(om1)); omega_set.add(int(om2)); omega_set.add(-int(om2))
    omegas = np.asarray(sorted(omega_set), dtype=int)
    idx = {int(o): i for i, o in enumerate(omegas.tolist())}
    mean = np.zeros(len(omegas), dtype=np.complex128)
    for om, c in mean_dict.items():
        mean[idx[int(om)]] = c
    second_raw = np.zeros((len(omegas), len(omegas)), dtype=np.complex128)
    for (om1, om2), c in moment.items():
        if int(om1) in idx and int(om2) in idx:
            second_raw[idx[int(om1)], idx[int(om2)]] = c
    # Desired covariance uses conjugated second index: E[a_omega conj(a_omega')]
    second_conj = np.zeros_like(second_raw)
    for om in omegas:
        for omp in omegas:
            second_conj[idx[int(om)], idx[int(omp)]] = moment.get((int(om), -int(omp)), 0 + 0j)
    Cov = second_conj - mean[:, None] * mean.conj()[None, :]
    # Numerical symmetrisation.
    Cov = 0.5 * (Cov + Cov.conj().T)
    return omegas, mean, second_raw, second_conj, Cov


def corr_from_cov(Cov: np.ndarray) -> np.ndarray:
    d = np.real(np.diag(Cov))
    denom = np.sqrt(np.maximum(d, 0.0))
    Corr = np.zeros_like(Cov)
    mask = denom > 1e-14
    Corr[np.ix_(mask, mask)] = Cov[np.ix_(mask, mask)] / np.outer(denom[mask], denom[mask])
    return Corr


def offdiag_ratio(A: np.ndarray) -> float:
    if A.size == 0 or A.shape[0] <= 1:
        return 0.0
    B = np.array(A, copy=True)
    np.fill_diagonal(B, 0)
    den = np.linalg.norm(A)
    return float(np.linalg.norm(B) / den) if den > 0 else 0.0


def effective_rank_psd(A: np.ndarray) -> float:
    if A.size == 0:
        return 0.0
    vals = np.linalg.eigvalsh(0.5 * (A + A.conj().T))
    vals = np.maximum(np.real(vals), 0.0)
    s1 = float(np.sum(vals)); s2 = float(np.sum(vals * vals))
    return (s1 * s1 / s2) if s2 > 0 else 0.0


def make_plots(out_dir: Path, omegas: np.ndarray, Cov: np.ndarray, Corr: np.ndarray, mean: np.ndarray, title: str) -> List[str]:
    made: List[str] = []
    if plt is None:
        return made

    def ticks(ax, axis: str) -> None:
        if len(omegas) <= 17:
            locs = np.arange(len(omegas)); labs = [str(int(o)) for o in omegas]
        else:
            locs = np.linspace(0, len(omegas) - 1, 9).round().astype(int); labs = [str(int(omegas[i])) for i in locs]
        if axis == "x":
            ax.set_xticks(locs, labs)
        else:
            ax.set_yticks(locs, labs)

    for arr, name, fname in [
        (np.real(Cov), r"$\operatorname{Re}\,\mathrm{Cov}[a_\omega,a_{\omega'}]$", "cov_real_heatmap.png"),
        (np.abs(Corr), r"$|\mathrm{Corr}[a_\omega,a_{\omega'}]|$", "corr_abs_heatmap.png"),
    ]:
        fig, ax = plt.subplots(figsize=(5.8, 5.1))
        im = ax.imshow(arr, origin="lower", aspect="equal")
        ax.set_title(name)
        ax.set_xlabel(r"actual $\omega'$"), ax.set_ylabel(r"actual $\omega$")
        ticks(ax, "x"); ticks(ax, "y")
        fig.colorbar(im, ax=ax, fraction=0.045, pad=0.04)
        fig.tight_layout(); fig.savefig(out_dir / fname, dpi=220); plt.close(fig)
        made.append(fname)

    fig, axes = plt.subplots(1, 3, figsize=(15.0, 4.2))
    axes[0].stem(omegas, np.real(np.diag(Cov)))
    axes[0].set_xlabel(r"$\omega$"); axes[0].set_ylabel(r"$\mathrm{Var}[a_\omega]$"); axes[0].set_title("Exact variance profile")
    im = axes[1].imshow(np.abs(Corr), origin="lower", aspect="equal")
    axes[1].set_title(r"$|\mathrm{Corr}|$"); ticks(axes[1], "x"); ticks(axes[1], "y")
    fig.colorbar(im, ax=axes[1], fraction=0.045, pad=0.04)
    axes[2].bar(["offdiag Cov", "offdiag Corr", "eff rank"], [offdiag_ratio(Cov), offdiag_ratio(Corr), effective_rank_psd(Cov)])
    axes[2].tick_params(axis="x", rotation=20)
    axes[2].set_title("Summary metrics")
    fig.suptitle(title)
    fig.tight_layout(); fig.savefig(out_dir / "exact_covariance_summary.png", dpi=220); plt.close(fig)
    made.append("exact_covariance_summary.png")
    return made


def save_matrix_csv(path: Path, omegas: np.ndarray, A: np.ndarray) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["omega\\omega_prime"] + [int(o) for o in omegas])
        for i, om in enumerate(omegas):
            writer.writerow([int(om)] + [complex(A[i, j]) for j in range(len(omegas))])


def parse_period(s: str) -> float:
    ss = str(s).strip().lower().replace(" ", "")
    if ss in ("2pi", "2*pi"):
        return 2.0 * math.pi
    if ss in ("4pi", "4*pi"):
        return 4.0 * math.pi
    return float(s)


def validate_mc(args, omegas: np.ndarray, Cov_exact: np.ndarray, mean_exact: np.ndarray, out_dir: Path) -> Optional[dict]:
    n_samples = int(args.validate_mc_samples)
    if n_samples <= 0:
        return None
    try:
        if args.ansatze_path:
            sys.path.insert(0, str(Path(args.ansatze_path).expanduser().resolve()))
        from ansatze import CircuitSpec, build_qnode  # type: ignore
        import jax  # type: ignore
        import jax.numpy as jnp  # type: ignore
    except Exception as exc:
        (out_dir / "mc_validation_error.txt").write_text(f"Import failed: {exc}\n", encoding="utf-8")
        return {"status": "import_failed", "error": str(exc)}

    try:
        spec = CircuitSpec(
            ansatz=args.ansatz,
            n_qubits=args.n_qubits,
            n_layers=args.n_layers,
            train_depth=args.train_depth,
            encoder_axis=args.encoder_axis,
            encoder_scale=float(args.encoder_scale),
            obs_kind=args.obs_kind,
            device_name="default.qubit",
            diff_method="backprop",
            jit=True,
        )
        qnode, m = build_qnode(spec)
        f_vmap_x = jax.jit(jax.vmap(qnode, in_axes=(0, None)))
        rng = np.random.default_rng(int(args.seed) + 104729)
        x = np.linspace(0.0, 2.0 * np.pi, int(args.n_x_mc), endpoint=False)
        Phi = np.exp(-1j * np.outer(omegas.astype(float), x)) / float(len(x))
        A = np.zeros((n_samples, len(omegas)), dtype=np.complex128)
        batch = int(args.mc_batch_size)
        done = 0
        t0 = time.time()
        while done < n_samples:
            b = min(batch, n_samples - done)
            thetas = rng.uniform(0.0, parse_period(args.theta_period), size=(b, int(m)))
            for j in range(b):
                y = np.asarray(f_vmap_x(jnp.asarray(x), jnp.asarray(thetas[j])), dtype=np.float64)
                A[done + j, :] = Phi @ y
            done += b
            if args.progress:
                elapsed = time.time() - t0
                rate = done / max(elapsed, 1e-12)
                eta = (n_samples - done) / max(rate, 1e-12)
                print(
                    f"MC validation {done}/{n_samples} "
                    f"rate={rate:.2f} samples/s "
                    f"elapsed={_fmt_seconds(elapsed)} eta={_fmt_seconds(eta)}",
                    flush=True,
                )
        mean_mc = np.mean(A, axis=0)
        Ac = A - mean_mc[None, :]
        Cov_mc = (Ac.T @ Ac.conj()) / float(n_samples)
        np.savez_compressed(out_dir / "mc_validation.npz", omegas=omegas, mean_mc=mean_mc, Cov_mc=Cov_mc, mean_exact=mean_exact, Cov_exact=Cov_exact)
        save_matrix_csv(out_dir / "mc_covariance.csv", omegas, Cov_mc)
        rel_frob = float(np.linalg.norm(Cov_exact - Cov_mc) / max(1e-15, np.linalg.norm(Cov_mc)))
        align = float(np.real(np.vdot(Cov_exact, Cov_mc)) / max(1e-15, np.linalg.norm(Cov_exact) * np.linalg.norm(Cov_mc)))
        mean_err = float(np.linalg.norm(mean_exact - mean_mc) / max(1e-15, np.linalg.norm(mean_mc)))
        return {"status": "ok", "n_samples": n_samples, "n_x": int(args.n_x_mc), "relative_frobenius_cov": rel_frob, "frobenius_alignment_cov": align, "relative_mean_error": mean_err, "npz": "mc_validation.npz"}
    except Exception as exc:
        (out_dir / "mc_validation_error.txt").write_text(f"Validation failed: {exc}\n", encoding="utf-8")
        return {"status": "failed", "error": str(exc)}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--out_dir", required=True)
    p.add_argument("--ansatz", required=True)
    p.add_argument("--n_qubits", type=int, required=True)
    p.add_argument("--n_layers", type=int, default=1)
    p.add_argument("--train_depth", type=int, required=True)
    p.add_argument("--encoder_axis", default="RX", choices=["RX", "RY", "RZ"])
    p.add_argument("--encoder_scale", default="1")
    p.add_argument("--obs_kind", default="OZ", choices=["OX", "OY", "OZ", "OZZ"])
    p.add_argument("--theta_period", default="2pi", help="Parameter averaging interval length. Use 4pi for full PennyLane CRX/CRZ unitary periodicity.")
    p.add_argument("--cr_quadrature_points", type=int, default=64)
    p.add_argument("--combine_tol", type=float, default=1e-14)
    p.add_argument("--max_states", type=int, default=20_000_000)
    p.add_argument("--progress", action="store_true")
    p.add_argument("--ansatze_path", default=None)
    p.add_argument("--validate_mc_samples", type=int, default=0)
    p.add_argument("--n_x_mc", type=int, default=128)
    p.add_argument("--mc_batch_size", type=int, default=32)
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args(argv)

    out_dir = Path(args.out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    t0 = time.time()
    encoder_scale = int(round(float(args.encoder_scale)))
    if abs(float(args.encoder_scale) - encoder_scale) > 1e-12:
        raise ValueError("This script currently requires integer encoder_scale")
    theta_period = parse_period(args.theta_period)

    ops, m = build_forward_ops(args.ansatz, args.n_qubits, args.n_layers, args.train_depth, args.encoder_axis, encoder_scale)
    obs = observable_terms(args.n_qubits, args.obs_kind, args.ansatz)

    # Precompute controlled-rotation maps only if needed.
    cr_axes = sorted({op.axis for op in ops if op.kind == "cr" and op.axis is not None})
    cr_single_maps: Dict[str, List[List[Tuple[int, complex]]]] = {}
    cr_pair_maps: Dict[str, List[List[Tuple[int, int, complex]]]] = {}
    for axis in cr_axes:
        if args.progress:
            print(f"precomputing CR{axis[-1]} twirl maps with {args.cr_quadrature_points} points over period {theta_period}", flush=True)
        smap, pmap = build_cr_maps(str(axis), int(args.cr_quadrature_points), theta_period, float(args.combine_tol))
        cr_single_maps[str(axis)] = smap
        cr_pair_maps[str(axis)] = pmap

    if args.progress:
        print(f"built circuit: ansatz={args.ansatz} n={args.n_qubits} L={args.n_layers} d={args.train_depth} m={m} ops={len(ops)}", flush=True)

    mean_omegas, mean_vals_small, mean_terminal = exact_mean(ops, obs, args.n_qubits, cr_single_maps, float(args.combine_tol), int(args.max_states), bool(args.progress))
    mean_dict = {int(o): complex(v) for o, v in zip(mean_omegas.tolist(), mean_vals_small.tolist())}
    moment, second_terminal = exact_second_moment(ops, obs, args.n_qubits, cr_pair_maps, float(args.combine_tol), int(args.max_states), bool(args.progress))
    omegas, mean, second_raw, second_conj, Cov = assemble_matrices(mean_dict, moment)
    Corr = corr_from_cov(Cov)

    save_matrix_csv(out_dir / "exact_covariance.csv", omegas, Cov)
    save_matrix_csv(out_dir / "exact_correlation.csv", omegas, Corr)
    np.savez_compressed(
        out_dir / "exact_twirled_covariance.npz",
        omegas=omegas,
        mean=mean,
        second_raw=second_raw,
        second_conj=second_conj,
        Cov=Cov,
        Corr=Corr,
    )
    plots = make_plots(out_dir, omegas, Cov, Corr, mean, f"{args.ansatz}, n={args.n_qubits}, L={args.n_layers}, d={args.train_depth}")
    mc_validation = validate_mc(args, omegas, Cov, mean, out_dir)

    summary = {
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "ansatz": args.ansatz,
        "n_qubits": int(args.n_qubits),
        "n_layers": int(args.n_layers),
        "train_depth": int(args.train_depth),
        "encoder_axis": args.encoder_axis,
        "encoder_scale": args.encoder_scale,
        "obs_kind": args.obs_kind,
        "theta_period": args.theta_period,
        "theta_period_float": theta_period,
        "m_parameters": int(m),
        "n_forward_ops": int(len(ops)),
        "n_observable_terms": int(len(obs)),
        "n_mean_terminal_terms": int(len(mean_terminal)),
        "n_second_terminal_terms": int(len(second_terminal)),
        "n_second_moment_entries": int(len(moment)),
        "n_omega": int(len(omegas)),
        "omega_min": int(np.min(omegas)) if len(omegas) else None,
        "omega_max": int(np.max(omegas)) if len(omegas) else None,
        "cov_frobenius_norm": float(np.linalg.norm(Cov)),
        "corr_offdiag_ratio": offdiag_ratio(Corr),
        "cov_offdiag_ratio": offdiag_ratio(Cov),
        "cov_effective_rank": effective_rank_psd(Cov),
        "runtime_seconds": float(time.time() - t0),
        "cr_axes": cr_axes,
        "cr_quadrature_points": int(args.cr_quadrature_points),
        "mc_validation": mc_validation,
        "plots": plots,
        "outputs": {
            "npz": "exact_twirled_covariance.npz",
            "covariance_csv": "exact_covariance.csv",
            "correlation_csv": "exact_correlation.csv",
            "summary_plot": "exact_covariance_summary.png" if "exact_covariance_summary.png" in plots else None,
            "covariance_heatmap": "cov_real_heatmap.png" if "cov_real_heatmap.png" in plots else None,
            "correlation_heatmap": "corr_abs_heatmap.png" if "corr_abs_heatmap.png" in plots else None,
            "mc_validation_npz": "mc_validation.npz" if mc_validation and mc_validation.get("status") == "ok" else None,
        },
        "method_note": "Exact two-copy parameter-twirled Heisenberg propagation computes C P C^dagger directly, avoiding explicit enumeration of k-columns.",
    }
    with open(out_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    with open(out_dir / "results_summary.txt", "w", encoding="utf-8") as f:
        f.write(json.dumps(summary, indent=2))
        f.write("\n")

    print(json.dumps(summary, indent=2))
    print(f"\nSaved exact twirled covariance outputs to: {out_dir}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
